staging_server:
  deploy_path: /var/www/vhosts/nstam.gr/staging.roomescaper.gr
  hostname: staging.roomescaper.gr
  identityFile: ~/.ssh/id_rsa
  port: 2234
  sshOptions:
    StrictHostKeyChecking: no
  stage: staging
  user: nstamato588453

production_server:
  deploy_path: /var/www/vhosts/nstam.gr/roomescaper.gr
  hostname: roomescaper.gr
  identityFile: ~/.ssh/id_rsa
  port: 2234
  sshOptions:
    StrictHostKeyChecking: no
  stage: production
  user: nstamato588453
